### ISSUE TITLE
Console warning

### ISSUE THREAD

**Issue by superfunkminister** [brohlson/chaseohlson#645]
Hey! Cool plugin, however I'm getting the following warning in the console:

`External link #watch was detected in a Link component. Use the Link component only for internal links. See: https://gatsby.dev/internal-links`.

**Comment by brohlson** [comment]
@superfunkminister  You're probably talking about https://github.com/brohlson/gatsby-plugin-anchor-links - you're formatting the hashed path incorrectly.  Should be `/#watch` or `/about#watch` with the path baked in.
